// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/punitj12/patient-app-gofr/internal/services (interfaces: PatientServicer)

// Package services is a generated GoMock package.
package services

import (
	gofr "developer.zopsmart.com/go/gofr/pkg/gofr"
	gomock "github.com/golang/mock/gomock"
	models "github.com/punitj12/patient-app-gofr/internal/models"
	reflect "reflect"
)

// MockPatientServicer is a mock of PatientServicer interface
type MockPatientServicer struct {
	ctrl     *gomock.Controller
	recorder *MockPatientServicerMockRecorder
}

// MockPatientServicerMockRecorder is the mock recorder for MockPatientServicer
type MockPatientServicerMockRecorder struct {
	mock *MockPatientServicer
}

// NewMockPatientServicer creates a new mock instance
func NewMockPatientServicer(ctrl *gomock.Controller) *MockPatientServicer {
	mock := &MockPatientServicer{ctrl: ctrl}
	mock.recorder = &MockPatientServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPatientServicer) EXPECT() *MockPatientServicerMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockPatientServicer) Create(arg0 *gofr.Context, arg1 *models.Patient) (*models.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*models.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockPatientServicerMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPatientServicer)(nil).Create), arg0, arg1)
}

// Delete mocks base method
func (m *MockPatientServicer) Delete(arg0 *gofr.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockPatientServicerMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPatientServicer)(nil).Delete), arg0, arg1)
}

// Get mocks base method
func (m *MockPatientServicer) Get(arg0 *gofr.Context, arg1 int) (*models.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockPatientServicerMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPatientServicer)(nil).Get), arg0, arg1)
}

// GetAll mocks base method
func (m *MockPatientServicer) GetAll(arg0 *gofr.Context) ([]*models.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]*models.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockPatientServicerMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPatientServicer)(nil).GetAll), arg0)
}

// Update mocks base method
func (m *MockPatientServicer) Update(arg0 *gofr.Context, arg1 *models.Patient) (*models.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*models.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockPatientServicerMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPatientServicer)(nil).Update), arg0, arg1)
}
